version: '3.8'

name: owner-container
services:
  app:
    image: 'quarkus/owner-service'
    container_name: "owner-app"
    ports:
      - '8080:8080'
    links:
      - "owner-db"
    environment:
      - DB_USER=root
      - DB_PWD=root
      - DB_URL=jdbc:mysql://mysql-db/owner

  owner-db:
    image: mysql:8.0
    container_name: "owner-db"
    environment:
      - MYSQL_DATABASE=owner
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - owner:/var/lib/mysql
      - ./../../../db/sql/create_owner_schemas.sql:/docker-entrypoint-initdb.d/create_owner_schemas.sql
volumes:
  owner:
    driver: local